export { default as About } from './About'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as Services } from './Services'
export { default as Team } from './Team'
export { default as Testimonials } from './Testimonials'
export { default as Work } from './Work'
